language: php
php:
  - '7.4'

install:
  - composer install

# Disable x-debug to speed up things
before_install: phpenv config-rm xdebug.ini

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  include:
    - stage: Tests
      script: php vendor/bin/psalm
      name: "static analysis"
    - script: php vendor/bin/codecept run
      name: "unit tests"
